import json
from pathlib import Path

notebook_path = Path(r"d:\Proy\AntiG\MIA\NLP\TrabajoFinal\finetuning_llm.ipynb")

with open(notebook_path, 'r', encoding='utf-8') as f:
    nb = json.load(f)

# The new advanced code for Punto 0 with MANY scenarios
advanced_generator_code = [
    "import json\n",
    "import os\n",
    "import random\n",
    "from pathlib import Path\n",
    "\n",
    "# 🔧 Rutas de entrada y salida\n",
    "CRITERIA_FILE = Path(r\"./prompt/indicaciones_gestion_requerimiento.json\")\n",
    "ANALYSIS_DIR = Path(r\"./output/greeting_analysis\")\n",
    "OUTPUT_DIR = Path(r\"./data/pomptsft\")\n",
    "OUTPUT_DIR.mkdir(parents=True, exist_ok=True)\n",
    "DATASET_FILE = OUTPUT_DIR / \"dataset_audit.jsonl\"\n",
    "\n",
    "def generate_systematic_scenarios():\n",
    "    \"\"\"Genera una amplia variedad de combinaciones de cumplimiento/incumplimiento.\"\"\"\n",
    "    scenarios = []\n",
    "    \n",
    "    # --- R1 + R3 + R4 (Validación OK, Retención Excesiva) ---\n",
    "    scenarios.append({\n",
    "        \"input\": \"Cliente: Quiero la baja.\\nAsesor: Nombre, DNI, fecha, lugar y monto por favor.\\nCliente: Juan López, 1234, 01/01/80, Lima, 50 soles.\\nAsesor: Gracias. Antes le ofrezco un descuento (1).\\nCliente: No.\\nAsesor: Y megas gratis (2).\\nCliente: No.\\nAsesor: ¿Un equipo? (3).\\nCliente: No, baja.\\nAsesor: ¿Y si le bajamos la mitad? (4).\\nCliente: Que no, ya le dije.\",\n",
    "        \"analysis\": {\n",
    "            \"R1_validacion_datos\": {\"cumple\": True, \"razon\": \"Validación completa realizada.\", \"score\": 10},\n",
    "            \"R3_ofertas_adecuadas\": {\"cumple\": False, \"razon\": \"Superó el límite de 3 ofertas.\", \"score\": 0},\n",
    "            \"R4_respeto_decision\": {\"cumple\": False, \"razon\": \"No respetó la decisión tras agotar ofertas.\", \"score\": 0}\n",
    "        }\n",
    "    })\n",
    "\n",
    "    # --- R1 + R7 (Validación OK, Espera Excesiva) ---\n",
    "    scenarios.append({\n",
    "        \"input\": \"Cliente: Baja por favor.\\nAsesor: Deme sus 5 datos de validación.\\nCliente: (Datos brindados correctamente).\\nAsesor: Espere en línea por favor.\\n(15 minutos de silencio sin avisar)...\\nCliente: ¿Hola? ¿Hay alguien? Me voy a cansar de esperar.\",\n",
    "        \"analysis\": {\n",
    "            \"R1_validacion_datos\": {\"cumple\": True, \"razon\": \"Validación correcta.\", \"score\": 10},\n",
    "            \"R7_tiempo_espera_justificado\": {\"cumple\": False, \"razon\": \"Espera de 15 minutos injustificada y sin contacto.\", \"score\": 0}\n",
    "        }\n",
    "    })\n",
    "\n",
    "    # --- R1 + R2 (Validación Incompleta + Mala Actitud) ---\n",
    "    scenarios.append({\n",
    "        \"input\": \"Cliente: Quiero cancelar el servicio.\\nAsesor: Nombre y DNI.\\nCliente: Maria, 123.\\nAsesor: Ya, espere. (Tono molesto)\\nCliente: ¿Me va a ayudar?\\nAsesor: Si no me deja trabajar no puedo, señora.\",\n",
    "        \"analysis\": {\n",
    "            \"R1_validacion_datos\": {\"cumple\": False, \"razon\": \"No pidió validación completa para baja.\", \"score\": 0},\n",
    "            \"R2_empatia_claridad\": {\"cumple\": False, \"razon\": \"Tono confrontativo y falta de cortesía.\", \"score\": 0}\n",
    "        }\n",
    "    })\n",
    "\n",
    "    # --- R6A + R2 (Cumple en información, pero sin empatía) ---\n",
    "    scenarios.append({\n",
    "        \"input\": \"Cliente: Necesito mi código de baja de ayer.\\nAsesor: El código es BJ-100. ¿Algo más? (Tono apurado y seco)\\nCliente: No, gracias.\",\n",
    "        \"analysis\": {\n",
    "            \"R6A_consulta_baja_previa\": {\"cumple\": True, \"razon\": \"Brindó el código solicitado.\", \"score\": 10},\n",
    "            \"R2_empatia_claridad\": {\"cumple\": False, \"razon\": \"Tono seco y apurado, falta calidez.\", \"score\": 5}\n",
    "        }\n",
    "    })\n",
    "\n",
    "    # --- R1 + R5 (Validación OK, pero Cierre Incompleto) ---\n",
    "    scenarios.append({\n",
    "        \"input\": \"Cliente: Baja definitiva por favor.\\nAsesor: (Valida todos los datos correctamente).\\nAsesor: Listo, ya está hecha su baja. Hasta luego.\",\n",
    "        \"analysis\": {\n",
    "            \"R1_validacion_datos\": {\"cumple\": True, \"razon\": \"Validación completa OK.\", \"score\": 10},\n",
    "            \"R5_formalizacion_cierre\": {\"cumple\": False, \"razon\": \"No indicó código de atención ni plazos de ejecución.\", \"score\": 0}\n",
    "        }\n",
    "    })\n",
    "\n",
    "    # --- R1 (Excepción: No es baja, es consulta) ---\n",
    "    scenarios.append({\n",
    "        \"input\": \"Cliente: ¿Cuando vence mi recibo?\\nAsesor: ¿Me da su nombre y DNI?\\nCliente: Juan, 444.\\nAsesor: Vence el 20 de este mes.\",\n",
    "        \"analysis\": {\n",
    "            \"R1_validacion_datos\": {\"cumple\": True, \"razon\": \"Identificación básica suficiente para consulta general.\", \"score\": 10}\n",
    "        }\n",
    "    })\n",
    "\n",
    "    # --- R1 + R9 (Corte por Cliente) ---\n",
    "    scenarios.append({\n",
    "        \"input\": \"Cliente: Baja por favor.\\nAsesor: Nombre, DNI, fecha, lugar y monto.\\nCliente: Juan López, 1234, 01/01/80... espere...\\n(Se corta la llamada por parte del cliente)\",\n",
    "        \"analysis\": {\n",
    "            \"R1_validacion_datos\": {\"cumple\": True, \"razon\": \"Asesor aplicó el protocolo correctamente antes del corte.\", \"score\": 10},\n",
    "            \"R9_falta_informacion\": {\"cumple\": \"NO APLICA\", \"razon\": \"Corte por cliente antes de completar gestión.\", \"score\": 0}\n",
    "        }\n",
    "    })\n",
    "\n",
    "    # --- R8 (Rebatimientos al límite: 3 intentos) ---\n",
    "    scenarios.append({\n",
    "        \"input\": \"Cliente: Me voy de la compañía.\\nAsesor: ¿Me permite ofrecerle A? (1)\\nCliente: No.\\nAsesor: ¿Y B? (2)\\nCliente: No.\\nAsesor: Una última opción de C? (3)\\nCliente: No, solo la baja.\",\n",
    "        \"analysis\": {\n",
    "            \"R8_regla_rebatimientos\": {\"cumple\": True, \"razon\": \"Realizó exactamente 3 rebatimientos, cumple el límite.\", \"score\": 10}\n",
    "        }\n",
    "    })\n",
    "    \n",
    "    return scenarios\n",
    "\n",
    "def generate_training_data():\n",
    "    print(\"🚀 Generando dataset altamente combinado...\")\n",
    "    \n",
    "    with open(CRITERIA_FILE, 'r', encoding='utf-8') as f:\n",
    "        criteria = json.load(f)\n",
    "    reglas_keys = list(criteria.get(\"reglas\", {}).keys())\n",
    "    \n",
    "    dataset = []\n",
    "    \n",
    "    # Archivos Reales\n",
    "    if ANALYSIS_DIR.exists():\n",
    "        files = list(ANALYSIS_DIR.glob(\"*.json\"))\n",
    "        for file in files:\n",
    "            try:\n",
    "                with open(file, 'r', encoding='utf-8') as f:\n",
    "                    data = json.load(f)\n",
    "                if \"transcription_text\" in data and \"rule_analysis\" in data:\n",
    "                    dataset.append({\n",
    "                        \"instruction\": f\"Analiza esta transcripción según las reglas {reglas_keys}.\",\n",
    "                        \"input\": data[\"transcription_text\"],\n",
    "                        \"output\": json.dumps({\"rule_analysis\": data[\"rule_analysis\"]}, ensure_ascii=False)\n",
    "                    })\n",
    "            except: continue\n",
    "\n",
    "    # Escenarios Sintéticos Combinados\n",
    "    synthetic = generate_systematic_scenarios()\n",
    "    for item in synthetic:\n",
    "        dataset.append({\n",
    "            \"instruction\": \"Realiza una auditoría de calidad detallada de este diálogo.\",\n",
    "            \"input\": item[\"input\"],\n",
    "            \"output\": json.dumps({\"rule_analysis\": item[\"analysis\"]}, ensure_ascii=False)\n",
    "        })\n",
    "    \n",
    "    random.shuffle(dataset)\n",
    "    with open(DATASET_FILE, 'w', encoding='utf-8') as f:\n",
    "        for entry in dataset:\n",
    "            f.write(json.dumps(entry, ensure_ascii=False) + \"\\n\")\n",
    "    \n",
    "    print(f\"✅ DATASET CONTRUIDO CON {len(dataset)} EJEMPLOS.\")\n",
    "\n",
    "generate_training_data()"
]

# Replacement logic
found = False
for cell in nb['cells']:
    if cell['cell_type'] == 'code' and 'generate_training_data()' in "".join(cell['source']):
        cell['source'] = advanced_generator_code
        found = True
        break

if found:
    with open(notebook_path, 'w', encoding='utf-8') as f:
        json.dump(nb, f, ensure_ascii=False, indent=1)
    print("Notebook updated with even more complex scenarios.")
else:
    print("Error updating notebook.")
