import json
from pathlib import Path

notebook_path = Path(r"d:\Proy\AntiG\MIA\NLP\TrabajoFinal\finetuning_llm.ipynb")

with open(notebook_path, 'r', encoding='utf-8') as f:
    nb = json.load(f)

# The ultra-advanced code for Punto 0
full_generator_code = [
    "import json\n",
    "import os\n",
    "import random\n",
    "from pathlib import Path\n",
    "\n",
    "CRITERIA_FILE = Path(r\"./prompt/indicaciones_gestion_requerimiento.json\")\n",
    "ANALYSIS_DIR = Path(r\"./output/greeting_analysis\")\n",
    "OUTPUT_DIR = Path(r\"./data/pomptsft\")\n",
    "OUTPUT_DIR.mkdir(parents=True, exist_ok=True)\n",
    "DATASET_FILE = OUTPUT_DIR / \"dataset_audit.jsonl\"\n",
    "\n",
    "def generate_all_rules_data(n_samples=2500):\n",
    "    \"\"\"Generador masivo que cubre R1 hasta R9 con todas sus variantes.\"\"\"\n",
    "    \n",
    "    names = [\"Juan Pérez\", \"María García\", \"Carlos Ruiz\", \"Ana Torres\", \"Luis Vega\", \"Elena Sol\"]\n",
    "    dnis = [\"11223344\", \"55667788\", \"99001122\", \"33445566\", \"77889900\"]\n",
    "    dates = [\"01/01/1980\", \"15/05/1992\", \"20/12/1975\", \"10/10/1988\"]\n",
    "    places = [\"Lima\", \"Cusco\", \"Arequipa\", \"Trujillo\", \"Piura\"]\n",
    "    amounts = [\"45.50\", \"89.90\", \"120.00\", \"35.00\", \"150.25\"]\n",
    "    \n",
    "    dataset = []\n",
    "    print(f\"🚀 Generando {n_samples} ejemplos de entrenamiento con cobertura R1-R9...\")\n",
    "    \n",
    "    for _ in range(n_samples):\n",
    "        dialog = []\n",
    "        analysis = {}\n",
    "        intent = random.choice([\"BAJA\", \"CONSULTA\", \"RECLAMO\", \"BAJA_PREVIA\"])\n",
    "        name, dni, date, place, amt = [random.choice(lst) for lst in [names, dnis, dates, places, amounts]]\n",
    "        \n",
    "        # --- R1 / R1A: Validación ---\n",
    "        if intent == \"BAJA\":\n",
    "            is_compliant = random.choice([True, False])\n",
    "            is_interrupted = random.random() < 0.1 # 10% de probabilidad de corte\n",
    "            \n",
    "            if is_interrupted:\n",
    "                dialog.append(f\"Cliente: Quiero la baja.\\nAsesor: Por favor valide: nombre, dni, fecha, lugar y monto.\\nCliente: {name}, {dni}... espere...\\n(Llamada cortada por cliente)\")\n",
    "                analysis[\"R1_validacion_datos\"] = {\"cumple\": True, \"razon\": \"Asesor aplicó protocolo de baja antes del corte.\", \"score\": 10}\n",
    "                analysis[\"R9_falta_informacion\"] = {\"cumple\": \"NO APLICA\", \"razon\": \"Corte por cliente impide terminar.\", \"score\": 0}\n",
    "            elif is_compliant:\n",
    "                dialog.append(f\"Cliente: Quiero la baja.\\nAsesor: Necesito su Nombre, DNI, Fecha, Lugar y Monto.\\nCliente: {name}, {dni}, {date}, {place}, {amt} soles.\\nAsesor: Validado correctamente.\")\n",
    "                analysis[\"R1_validacion_datos\"] = {\"cumple\": True, \"razon\": \"Validación completa realizada.\", \"score\": 10}\n",
    "            else:\n",
    "                dialog.append(f\"Cliente: Quiero dar de baja mi línea.\\nAsesor: ¿DNI y nombre?\\nCliente: {dni}, {name}.\\nAsesor: Listo, procederemos.\")\n",
    "                analysis[\"R1_validacion_datos\"] = {\"cumple\": False, \"razon\": \"Omitió campos obligatorios (fecha, lugar, monto) para baja.\", \"score\": 0}\n",
    "        else:\n",
    "            dialog.append(f\"Cliente: Tengo una duda.\\nAsesor: Nombre y DNI.\\nCliente: {name}, {dni}.\\nAsesor: ¿En qué le ayudo?\")\n",
    "            analysis[\"R1_validacion_datos\"] = {\"cumple\": True, \"razon\": \"Identificación básica suficiente para gestión no sensible.\", \"score\": 10}\n",
    "\n",
    "        # --- R2: Empatía (Randomly add empathy issues) ---\n",
    "        r2_compliant = random.random() > 0.15\n",
    "        if not r2_compliant:\n",
    "            dialog.append(\"Asesor: (Tono molesto) Apúrese que tengo más llamadas.\\nCliente: No me hable así.\")\n",
    "            analysis[\"R2_empatia_claridad\"] = {\"cumple\": False, \"razon\": \"Asesor muestra falta de cortesía y tono confrontativo.\", \"score\": 0}\n",
    "        else:\n",
    "            analysis[\"R2_empatia_claridad\"] = {\"cumple\": True, \"razon\": \"Mantiene comunicación clara y respetuosa.\", \"score\": 10}\n",
    "\n",
    "        # --- R3 / R4 / R8: Retenciones y Rebatimientos ---\n",
    "        if intent == \"BAJA\":\n",
    "            n_offers = random.randint(1, 5)\n",
    "            for i in range(min(n_offers, 3)):\n",
    "                dialog.append(f\"Asesor: ¿Le interesa la oferta {i+1}?\\nCliente: No gracias.\")\n",
    "            if n_offers > 3:\n",
    "                dialog.append(f\"Asesor: Insisto con la oferta {n_offers}.\\nCliente: Ya dije que no.\")\n",
    "                analysis[\"R3_ofertas_adecuadas\"] = {\"cumple\": False, \"razon\": \"Superó el límite de 3 ofertas.\", \"score\": 0}\n",
    "                analysis[\"R4_respeto_decision\"] = {\"cumple\": False, \"razon\": \"No respetó la decisión tras 3 intentos.\", \"score\": 0}\n",
    "                analysis[\"R8_regla_rebatimientos\"] = {\"cumple\": False, \"razon\": \"Superó límite de rebatimientos permitidos.\", \"score\": 0}\n",
    "            else:\n",
    "                analysis[\"R3_ofertas_adecuadas\"] = {\"cumple\": True, \"razon\": \"Dentro del límite de 3 ofertas.\", \"score\": 10}\n",
    "                analysis[\"R4_respeto_decision\"] = {\"cumple\": True, \"razon\": \"Respeta decisión tras ofertas permitidas.\", \"score\": 10}\n",
    "                analysis[\"R8_regla_rebatimientos\"] = {\"cumple\": True, \"razon\": \"Rebatimientos realizados según política.\", \"score\": 10}\n",
    "        else:\n",
    "            # Si no es baja, no debe ofrecer retenciones\n",
    "            should_offer = random.choice([True, False]) if intent == \"CONSULTA\" else False\n",
    "            if should_offer:\n",
    "                 dialog.append(\"Asesor: Le ofrezco un descuento.\\nCliente: Pero solo pregunté mi saldo.\")\n",
    "                 # En consulta/facilidades no penaliza si ofrece? La regla dice: \n",
    "                 # \"Si no manifiesta deseo de baja... el asesor NO debe ofrecer retenciones... se considera CUMPLE al mantener el contexto\"\n",
    "                 # En el prompt original de la regla dice que \"se considera CUMPLE al mantener la conversación dentro del contexto correcto\".\n",
    "                 # Interpretación: Si ofrece cuando NO es baja, está fuera de contexto? \n",
    "                 # Corrijo: En consulta no debe ofrecer. Si ofrece, es NO CUMPLE en R3.\n",
    "                 analysis[\"R3_ofertas_adecuadas\"] = {\"cumple\": False, \"razon\": \"Ofreció retenciones en una gestión que no era de baja.\", \"score\": 0}\n",
    "            else:\n",
    "                 analysis[\"R3_ofertas_adecuadas\"] = {\"cumple\": True, \"razon\": \"No realizó ofertas fuera de contexto.\", \"score\": 10}\n",
    "\n",
    "        # --- R6A: Baja Previa ---\n",
    "        if intent == \"BAJA_PREVIA\":\n",
    "            r6a_compliant = random.choice([True, False])\n",
    "            if r6a_compliant:\n",
    "                dialog.append(f\"Asesor: El código de su baja anterior es {random.randint(111,999)}.\")\n",
    "                analysis[\"R6A_consulta_baja_previa\"] = {\"cumple\": True, \"razon\": \"Brinda información de baja previa correctamente.\", \"score\": 10}\n",
    "            else:\n",
    "                dialog.append(\"Asesor: No veo nada de bajas anteriores en mi pantalla.\")\n",
    "                analysis[\"R6A_consulta_baja_previa\"] = {\"cumple\": False, \"razon\": \"No asistió con información de gestión anterior.\", \"score\": 0}\n",
    "\n",
    "        # --- R7: Tiempo de Espera ---\n",
    "        wait_time = random.randint(1, 15)\n",
    "        if wait_time > 5 and intent == \"BAJA\":\n",
    "            dialog.append(f\"(Espera silenciosa de {wait_time} minutos sin motivo)\")\n",
    "            analysis[\"R7_tiempo_espera_justificado\"] = {\"cumple\": False, \"razon\": f\"Espera excesiva de {wait_time} min para dilatar baja.\", \"score\": 0}\n",
    "        else:\n",
    "            analysis[\"R7_tiempo_espera_justificado\"] = {\"cumple\": True, \"razon\": \"Tiempo en espera razonable.\", \"score\": 10}\n",
    "\n",
    "        # --- R5 / R6: Cierre y Resolución ---\n",
    "        cuts_at_end = random.random() < 0.05\n",
    "        if cuts_at_end:\n",
    "            dialog.append(\"(Cliente se desconecta antes de formalizar)\")\n",
    "            analysis[\"R5_formalizacion_cierre\"] = {\"cumple\": \"NO APLICA\", \"razon\": \"Corte imprevisto por cliente.\", \"score\": 0}\n",
    "            analysis[\"R6_resolver_consulta_asociada\"] = {\"cumple\": \"NO APLICA\", \"razon\": \"Corte impide resolución final.\", \"score\": 0}\n",
    "        else:\n",
    "            r5_compliant = random.choice([True, False])\n",
    "            if r5_compliant:\n",
    "                dialog.append(f\"Asesor: Gestión realizada. Código: ID-{random.randint(1,100)}, plazo 24h.\")\n",
    "                analysis[\"R5_formalizacion_cierre\"] = {\"cumple\": True, \"razon\": \"Formaliza con código y plazos.\", \"score\": 10}\n",
    "                analysis[\"R6_resolver_consulta_asociada\"] = {\"cumple\": True, \"razon\": \"Resuelve la solicitud principal.\", \"score\": 10}\n",
    "            else:\n",
    "                dialog.append(\"Asesor: Listo, chau.\")\n",
    "                analysis[\"R5_formalizacion_cierre\"] = {\"cumple\": False, \"razon\": \"No entregó código ni explicó plazos.\", \"score\": 0}\n",
    "                analysis[\"R6_resolver_consulta_asociada\"] = {\"cumple\": False, \"razon\": \"No brindó información final necesaria.\", \"score\": 0}\n",
    "\n",
    "        dataset.append({\n",
    "            \"instruction\": \"Genera un reporte de auditoría completo basado en esta transcripción, evaluando las reglas R1 a R9.\",\n",
    "            \"input\": \"\\n\".join(dialog),\n",
    "            \"output\": json.dumps({\"rule_analysis\": analysis}, ensure_ascii=False)\n",
    "        })\n",
    "    \n",
    "    # Integración de data real\n",
    "    if ANALYSIS_DIR.exists():\n",
    "        real_files = list(ANALYSIS_DIR.glob(\"*.json\"))\n",
    "        for f_path in real_files:\n",
    "            try:\n",
    "                with open(f_path, 'r', encoding='utf-8') as f:\n",
    "                    data = json.load(f)\n",
    "                if \"transcription_text\" in data and \"rule_analysis\" in data:\n",
    "                    dataset.append({\n",
    "                        \"instruction\": \"Genera un reporte de auditoría completo basado en esta transcripción.\",\n",
    "                        \"input\": data[\"transcription_text\"],\n",
    "                        \"output\": json.dumps({\"rule_analysis\": data[\"rule_analysis\"]}, ensure_ascii=False)\n",
    "                    })\n",
    "            except: continue\n",
    "\n",
    "    random.shuffle(dataset)\n",
    "    with open(DATASET_FILE, 'w', encoding='utf-8') as f:\n",
    "        for entry in dataset:\n",
    "            f.write(json.dumps(entry, ensure_ascii=False) + \"\\n\")\n",
    "    \n",
    "    print(f\"🎉 Dataset total construido con {len(dataset)} ejemplos (sintéticos + reales).\")\n",
    "    print(f\"📁 Archivo guardado en: {DATASET_FILE}\")\n",
    "\n",
    "generate_all_rules_data(n_samples=3000)\n"
]

# Find and replace Point 0
for cell in nb['cells']:
    if cell['cell_type'] == 'code' and 'generate_combinatorial_data' in "".join(cell['source']):
        cell['source'] = full_generator_code
        break

with open(notebook_path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)

print("Notebook updated with FULL SPECTRUM R1-R9 combinatorial generator.")
